apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: testconn
  name: testconn
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: testconn
status:
  loadBalancer: {}
